config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root 'users#home'
  get 'users/settings'
  get '/home', to: 'users#home'
  get '/about', to: 'users#about'
  get '/user_comments', to: 'users#user_comments'
  get '/user_projects', to: 'users#user_projects'
  get '/user_proposals', to: 'users#user_proposals'
  post '/search', to: 'search#search'

  devise_for :users

  resources :users
  resources :user_settings

  resources :comments

  resources :projects do
    resources :sponsor_proposals do
      get 'reject'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: [:index]
      resources :spheres, only: [:index]
    end
  end
end

app/models/project.rb
require 'elasticsearch/model'

class Project < ApplicationRecord
  include Elasticsearch::Model

  has_and_belongs_to_many :regions
  has_and_belongs_to_many :spheres
  has_and_belongs_to_many :requirements_phrases

  has_many :comments, as: :commentable, dependent: :destroy

  has_many :project_conditions
  has_many :sponsor_proposals, dependent: :destroy
  has_many :gradings
  belongs_to :user

  has_rich_text :development_plan

  validates :title, presence: true
  validates :description, presence: true

  paginates_per 5

  enum state: { active: 0, closed: 1 }
end

Project.__elasticsearch__.create_index!
Project.import

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_regions, :load_spheres, :load_conditions, only: %i[new edit]
  before_action :find_project, only: %i[show edit update destroy]

  def index
    authorize Project
    projects = Projects::Filter.new(current_user).do_filter
    @projects = Kaminari.paginate_array(projects).page(params[:page]).per(5)
  end

  def show
    @requirements_phrases = RequirementsPhrase.all
    authorize @project
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Projects::Creator.new(project_params, current_user).call
    authorize @project
    if @project
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
    authorize @project
  end

  def update
    authorize @project
    if @project.update(project_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    authorize @project
    @project.destroy
    redirect_to projects_path
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def load_regions
    @regions = Region.all
  end

  def load_conditions
    @conditions = RequirementsPhrase.for_sponsor
  end

  def load_spheres
    @spheres = Sphere.all
  end

  def project_params
    params.require(:project).permit(:title, :description, requirements_phrase_ids: [], region_ids: [], sphere_ids: [])
  end
end

app/helpers/project_helper.rb
module ProjectHelper
  def sponsor_proposals
    @project.sponsor_proposals.where({ status: 0 })
  end
end

app/views/projects/_form.html.erb
<section id="contact" class="contact" style="margin-top: 40px">
  <div class="container" data-aos="fade-up">
    <header class="section-header">
      <h2>Create New Project</h2>
    </header>
    <div class="col-lg-12">
      <%= simple_form_for @project do |form| %>            
        <div class="container">
          <div class="row">
            <div class="col">
              <%= form.collection_select(:region_ids, @regions, :id, :name, {:prompt => "Please Select a Regions"}, {:multiple => true, class: 'form-control', required: true }) %>
            </div>
            <div class="col">
              <%= form.collection_select(:sphere_ids, @spheres, :id, :name, {:prompt => "Please Select a Spheres"}, {:multiple => true, class: 'form-control', required: true }) %>
            </div>
            <div class="col">
              <%= form.collection_select(:requirements_phrase_ids, @conditions, :id, :name, {:prompt => "Please Select a Conditions"}, {:multiple => true, class: 'form-control', required: true }) %><br> 
            </div>
          </div>
        </div>

        <div class="row gy-4">
          <div class="col-md-12">
            <%= form.input :title, label: 'Your Project Title', input_html: { class: 'form-control' }, placeholder: "Your Project Title" %><br>
            <% @project.errors.full_messages_for(:title).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>

          <div class="col-md-12">
            <%= form.input :description, as: :text, label: 'Your Project Description', input_html: { class: 'form-control' }, placeholder: "Your Project Description" %><br>
            <% @project.errors.full_messages_for(:description).each do |message| %>
              <div><%= message %></div>
            <% end %>
          </div>
        </div>

        <div class="field">
          <%= form.label :development_plan %>
          <%= form.rich_text_area :development_plan %>
        </div>
          
          <%= form.submit 'Submit', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</section>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form", project: @project %>

app/views/projects/index.html.erb
<main id="main">
  <section id="about" class="about" style="margin-top: 40px">
    <div class="container" data-aos="fade-up">
      <div class="row gx-0">
        <div class="col-lg-12 d-flex flex-column justify-content-center" data-aos="fade-up" data-aos-delay="200">
          <% unless @projects.blank? %>
            <% @projects.each do |project| %>
              <div class="content" style="margin-top: 20px">
                <h3><%= project.title %></h3>
                <h2><%= project.description[0..150] %></h2>
                  <p>
                    Relevance in 
                    <% project.regions[0..3].each do |region| %>
                      <%= region.name %>
                    <% end %>
                    ...
                  </p>

                  <p>
                    Spheres:  
                    <% project.spheres[0..3].each do |sphere| %>
                      <%= sphere.name %>
                    <% end %>
                    ...
                  </p>

                  <p>
                    We expect 
                    <% project.requirements_phrases[0..3].each do |requirement| %>
                      <%= requirement.name %>
                    <% end %>
                    ...
                  </p>

                <div class="text-center text-lg-start">
                  <a href="<%= project_path(project) %>" class="btn-read-more d-inline-flex align-items-center justify-content-center align-self-center">
                    <span>Read More</span>
                    <i class="bi bi-arrow-right"></i>
                  </a>
                </div>
              </div>
            <% end %>
          <% else %>
            <h2> There aren't any projects yet( </h2>
          <% end %>

          <%= paginate @projects %>
        </div>
      </div>
    </div>
  </section>
</main>

app/views/projects/new.html.erb
<%= render "form", article: @project %>

app/views/projects/show.html.erb
<section id="faq"  class="about" style="margin-top: 40px">
  <div class="container" data-aos="fade-up">

    <header class="section-header">
      <h2><%= @project.title %></h2>
    </header>

    <div class="row">
      <div class="col-lg-12">
        <div class="accordion accordion-flush" id="faqlist1">
          <div class="accordion-item">
            <h2 class="accordion-header">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-1">
                Prospective Regions
              </button>
            </h2>
            <div id="faq-content-1" class="accordion-collapse collapse" data-bs-parent="#faqlist1">
              <div class="accordion-body">
                <p>
                  <% @project.regions.each do |region| %>
                    <%= region.name %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>

          <div class="accordion-item">
            <h2 class="accordion-header">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-2">
                Actual Spheres
              </button>
            </h2>
            <div id="faq-content-2" class="accordion-collapse collapse" data-bs-parent="#faqlist1">
              <div class="accordion-body">
                <p>
                  <% @project.spheres.each do |sphere| %>
                    <%= sphere.name %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>

          <div class="accordion-item">
            <h2 class="accordion-header">
              <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-3">
                Our Requirements
              </button>
            </h2>
            <div id="faq-content-3" class="accordion-collapse collapse" data-bs-parent="#faqlist1">
              <div class="accordion-body">
                <p>
                  <% @project.requirements_phrases.each do |requirement| %>
                    <%= requirement.name %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="content">
        <h2>Project Description: <%= @project.description %></h2>
    </div>
  </div>

</section>

<section id="contact" class="contact">
    <div class="container" data-aos="fade-up">
      <header class="section-header">
        <h2>Project Author - <%= @project.user.nick %></h2>
        <% if current_user == @project.user %>
          <div class="row gy-4">
            <div class="col-md-6">
              <a><%= link_to "Edit", edit_project_path(@project) %></a>
            </div>
            <div class="col-md-6">
              <a><%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: "Confirm" } %></a>
            </div>
          </div>
        <% end %>  
      </header>          

      <div class="row gy-4">
        <div class="col-lg-12">
          <div class="row gy-4">
            <div class="col-md-6">
              <div class="info-box">
                <i class="bi bi-envelope"></i>
                <h3>Email</h3>
                <p><%= @project.user.email %></p>
              </div>
            </div>
            <div class="col-md-6">
              <div class="info-box">
                <i class="bi bi-telephone"></i>
                <h3>Phone Number</h3>
                <p>Phone nado</p>
              </div>
            </div>
            <div class="col-md-6">
              <div class="info-box">
                <i class="bi bi-skype"></i>
                <h3>Skype</h3>
                <p>Skype nado</p>
              </div>
            </div>
            <div class="col-md-6">
              <div class="info-box">
                <i class="bi bi-telegram"></i>
                <h3>Telegram</h3>
                <p>Telegram nado</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

<section id="faq" class="faq">
  <div class="container" data-aos="fade-up">
    <div class="row">
      <div class="col-lg-6">
        <!-- comments-->
        <header class="section-header">
          <h2>Add a comment to project</h2>
        </header>
        <%= render partial: 'comments/form', locals: {commentable_type: 'Project', commentable_id: @project.id} %>

        <h3>Project comments</h3>
        <%= render @project.comments %>
      </div>

      <div class="col-lg-6">
        <!-- sponsor proposal-->
        <header class="section-header">
          <h2>Add a Sponsor proposal</h2>
        </header>
        <%= render sponsor_proposals %>

        <h3>Add a proposal to project:</h3>
        <%= render 'sponsor_proposals/form' %>
      </div>
    </div>
  </div>
</section>