config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root 'users#home'
  get 'users/settings'
  get '/home', to: 'users#home'
  get '/about', to: 'users#about'
  get '/user_comments', to: 'users#user_comments'
  get '/user_projects', to: 'users#user_projects'
  get '/user_proposals', to: 'users#user_proposals'
  post '/search', to: 'search#search'

  devise_for :users

  resources :users
  resources :user_settings

  resources :comments

  resources :projects do
    resources :sponsor_proposals do
      get 'reject'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: [:index]
      resources :spheres, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/grading.rb
class Grading < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
require 'elasticsearch/model'

class Project < ApplicationRecord
  include Elasticsearch::Model

  has_and_belongs_to_many :regions
  has_and_belongs_to_many :spheres
  has_and_belongs_to_many :requirements_phrases

  has_many :comments, as: :commentable, dependent: :destroy

  has_many :project_conditions
  has_many :sponsor_proposals, dependent: :destroy
  has_many :gradings
  belongs_to :user

  has_rich_text :development_plan

  validates :title, presence: true
  validates :description, presence: true

  paginates_per 5

  enum state: { active: 0, closed: 1 }
end

Project.__elasticsearch__.create_index!
Project.import

app/models/project_condition.rb
class ProjectCondition < ApplicationRecord
  has_and_belongs_to_many :projects
end

app/models/region.rb
class Region < ApplicationRecord
  has_and_belongs_to_many :projects
  has_many :user_settings, as: :settable
end

app/models/requirements_phrase.rb
class RequirementsPhrase < ApplicationRecord
  has_many :sponsor_conditions
  has_many :sponsor_proposals, through: :sponsor_conditions
  has_many :user_settings, as: :settable

  scope :for_sponsor, -> { where(purpose: :sponsor) }

  enum purpose: { sponsor: 0, project: 1 }
end

app/models/sphere.rb
class Sphere < ApplicationRecord
  has_and_belongs_to_many :projects
  has_many :user_settings, as: :settable
end

app/models/sponsar_condition.rb
# frozen_string_literal: true

class SponsorCondition < ApplicationRecord
  has_many :requirement_vocabularys
  belongs_to :sponsor_proposal
end

app/models/sponsar_proposal.rb
# frozen_string_literal: true

class SponsorProposal < ApplicationRecord
  has_many :sponsor_conditions
  belongs_to :project

  enum status: { open: 0, rejected: 1 }
end

app/models/sponsor_condition.rb
class SponsorCondition < ApplicationRecord
  belongs_to :sponsor_proposal
  belongs_to :requirements_phrase
end

app/models/sponsor_proposal.rb
class SponsorProposal < ApplicationRecord
  has_many :sponsor_conditions, dependent: :destroy
  has_many :requirements_phrases, through: :sponsor_conditions

  accepts_nested_attributes_for :sponsor_conditions

  belongs_to :project
  belongs_to :user

  enum status: { unblocked: 0, rejected: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :user_settings, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :sponsor_proposals, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :contact, dependent: :destroy

  enum role: { sponsor: 0, businessman: 1 }

  scope :sponsors, -> { where(role: 0) }
end

app/models/user_setting.rb
class UserSetting < ApplicationRecord
  belongs_to :user
  belongs_to :settable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:nick, :email, :password, :role, :about_me, :password_confirmation) }
  end

  def user_not_authorized
    redirect_to(request.referrer || rootpath)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(comment_params)
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :user_id, :commentable_id, :commentable_type)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_regions, :load_spheres, :load_conditions, only: %i[new edit]
  before_action :find_project, only: %i[show edit update destroy]

  def index
    authorize Project
    projects = Projects::Filter.new(current_user).do_filter
    @projects = Kaminari.paginate_array(projects).page(params[:page]).per(5)
  end

  def show
    @requirements_phrases = RequirementsPhrase.all
    authorize @project
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Projects::Creator.new(project_params, current_user).call
    authorize @project
    if @project
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
    authorize @project
  end

  def update
    authorize @project
    if @project.update(project_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    authorize @project
    @project.destroy
    redirect_to projects_path
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def load_regions
    @regions = Region.all
  end

  def load_conditions
    @conditions = RequirementsPhrase.for_sponsor
  end

  def load_spheres
    @spheres = Sphere.all
  end

  def project_params
    params.require(:project).permit(:title, :description, requirements_phrase_ids: [], region_ids: [], sphere_ids: [])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @search_list = Elasticsearch::Model.search(params[:text], Project).records.to_a
    respond_to do |format|
      format.js
      format.html { redirect_to root_path }
    end
  end
end

app/controllers/user_settings_controller.rb
class UserSettingsController < ApplicationController
  before_action :load_regions, :load_spheres, :load_requirements, only: :new

  def new
    @user_setting_form = UserSettingForm.new
  end

  def create
    @project = UserSettings::Creator.new(user_setting_params, current_user).call

    if @project
      redirect_to users_settings_path
    else
      render :new
    end
  end

  def destroy
    @user_setting = UserSetting.find(params[:id])
    @user_setting.destroy

    redirect_to users_settings_path
  end

  private

  def load_regions
    @regions = Region.all
  end

  def load_requirements
    @requirements = RequirementsPhrase.for_sponsor
  end

  def load_spheres
    @spheres = Sphere.all
  end

  def user_setting_params
    params.require(:user_setting_form).permit(:user_id, requirement_ids: [], sphere_ids: [], region_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :init_user, only: %i[show edit update]

  def settings
    @user_settings = current_user.user_settings
  end

  def home; end

  def about; end

  def show; end

  def user_comments
    @user_comments = current_user.comments
  end

  def user_projects
    @user_projects = current_user.projects.page params[:page]
  end

  def user_proposals
    @user_proposals = current_user.sponsor_proposals
  end

  def destroy
    current_user.destroy
  end

  def edit;  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def init_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:nick, :email)
  end
end

app/helpers/project_helper.rb
module ProjectHelper
  def sponsor_proposals
    @project.sponsor_proposals.where({ status: 0 })
  end
end

app/views/comments/_comment.html.erb
<div class="comment-wrapper <%= comment.commentable_type.downcase %>">
  <p>
    <strong>User:</strong>
    <%= comment.user.email %>
  </p>
  <p>
    <strong>User comment:</strong>
    <%= comment.text %>
  </p>
  <%= render partial: 'comments/form', locals: {commentable_type: 'Comment', commentable_id: comment.id} %>

  <%= render comment.comments, locals: {commentable_type: 'Project'} %>
</div>

<%
=begin%>
 <div class="accordion accordion-flush" id="faqlist2">
  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq2-content-1">
        Ac odio tempor orci dapibus. Aliquam eleifend mi in nulla?
      </button>
    </h2>
    <div id="faq2-content-1" class="accordion-collapse collapse" data-bs-parent="#faqlist2">
      <div class="accordion-body">
        Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit laoreet id donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est pellentesque elit ullamcorper dignissim. Mauris ultrices eros in cursus turpis massa tincidunt dui.
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq2-content-2">
        Tempus quam pellentesque nec nam aliquam sem et tortor consequat?
      </button>
    </h2>
    <div id="faq2-content-2" class="accordion-collapse collapse" data-bs-parent="#faqlist2">
      <div class="accordion-body">
        Molestie a iaculis at erat pellentesque adipiscing commodo. Dignissim suspendisse in est ante in. Nunc vel risus commodo viverra maecenas accumsan. Sit amet nisl suscipit adipiscing bibendum est. Purus gravida quis blandit turpis cursus in
      </div>
    </div>
  </div>

  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq2-content-3">
        Varius vel pharetra vel turpis nunc eget lorem dolor?
      </button>
    </h2>
    <div id="faq2-content-3" class="accordion-collapse collapse" data-bs-parent="#faqlist2">
      <div class="accordion-body">
        Laoreet sit amet cursus sit amet dictum sit amet justo. Mauris vitae ultricies leo integer malesuada nunc vel. Tincidunt eget nullam non nisi est sit amet. Turpis nunc eget lorem dolor sed. Ut venenatis tellus in metus vulputate eu scelerisque. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Nibh tellus molestie nunc non blandit massa enim nec.
      </div>
    </div>
  </div>
</div> 
<%
=end%>

app/views/comments/_form.html.erb
<%= simple_form_for Comment.new do |form| %>
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.hidden_field :commentable_id, value: commentable_id %>
    <%= form.hidden_field :commentable_type, value: commentable_type %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/user_settings/new.html.erb
<section id="pricing" class="pricing">
  <div class="container" data-aos="fade-up">
    <%= simple_form_for @user_setting_form, url: user_settings_path do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      
      <div class="container">
        <div class="row">
          <div class="col">
            <%= form.collection_select(:region_ids, @regions, :id, :name, {:prompt => "Please Select a Regions"}, {:multiple => true, class: 'form-control' }) %><br> 
          </div>
          <div class="col">
            <%= form.collection_select(:sphere_ids, @spheres, :id, :name, {:prompt => "Please Select a Spheres"}, {:multiple => true, class: 'form-control' }) %><br> 
          </div>
          <div class="col">
            <%= form.collection_select(:requirement_ids, @requirements, :id, :name, {:prompt => "Please Select a Requirements"}, {:multiple => true, class: 'form-control' }) %><br> 
          </div>
        </div>

        <div class="row">
          <div class="col">
            <%= form.submit 'Submit', class: 'btn btn-primary' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/users/about.html.erb
<main id="main">
  <section id="about" class="about">
    <div class="container" data-aos="fade-up">
      <div class="row gx-0">

        <div class="col-lg-6 d-flex flex-column justify-content-center" data-aos="fade-up" data-aos-delay="200">
          <div class="content">
            <h3>Sponsorship Platform</h3>
            <h2>My personal project at the second stage of the Students Lab in iTechArt Group!!!</h2>
            <p>
              Web-application for publishing startups ideas and searching sponsorships.
            </p>
          </div>
        </div>

        <div class="col-lg-6 d-flex align-items-center" data-aos="zoom-out" data-aos-delay="200">
          <img src="/assets/theme/img/about.jpg" class="img-fluid" alt="">
        </div>

      </div>
    </div>
  </section>
</main>

app/views/users/edit.html.erb
<section id="contact" class="contact">
  <div class="container" data-aos="fade-up">
    <header class="section-header">
      <h2>Edit My Profile</h2>
    </header>
    <div class="row gy-4">
      <div class="col-lg-12">
        <%= simple_form_for @user do |form| %>
          <div class="row gy-4">
            <div class="col md-6">
              <%= form.input :nick, label: 'Your Nick', input_html: { class: 'form-control' } %><br>
            </div>

            <div class="col md-6">
              <%= form.input :email, as: :text, label: 'Your Email', input_html: { class: 'form-control' } %><br>
            </div>
          </div>

          <div>
            <%= form.submit 'Submit', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/home.html.erb
<main id="main">
  <section id="hero" class="hero d-flex align-items-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 d-flex flex-column justify-content-center">
          <h1 data-aos="fade-up">Students Lab</h1>
          <h1 data-aos="fade-up">Remarkable People</h1>
          <h2 data-aos="fade-up" data-aos-delay="400">How you worked, so you earned</h2>
          <% if current_user.businessman? %>
            <div data-aos="fade-up" data-aos-delay="600">
              <div class="text-center text-lg-start">
                <a href="<%= new_project_path %>" class="btn-get-started scrollto d-inline-flex align-items-center justify-content-center align-self-center">
                  <span>Get Started</span>
                  <i class="bi bi-arrow-right"></i>
                </a>
              </div>
            </div>
          <% end %>
        </div>
        <div class="col-lg-6 hero-img" data-aos="zoom-out" data-aos-delay="200">
          <img src="/assets/theme/img/hero-img.png" class="img-fluid" alt="">
        </div>
      </div>
    </div>
  </section>
</main>

app/views/users/settings.html.erb
<section id="features" class="features">
  <div class="container" data-aos="fade-up">
    <div class="row feature-icons" data-aos="fade-up">
      <h3>Ratione mollitia eos ab laudantium rerum beatae quo</h3>

      <div class="row">

        <div class="col-xl-4 text-center" data-aos="fade-right" data-aos-delay="100">
          <img src="/assets/theme/img/features-3.png" class="img-fluid p-4" alt="">
        </div>

        <div class="col-xl-8 d-flex content">
          <div class="row align-self-center gy-4">
            <ul class="list-group list-group-flush">
              <% unless @user_settings.nil? %>
                <% @user_settings.each do |user_setting| %>
                  <li class="list-group-item"><h4><%= user_setting.settable.name %> <%= link_to " Delete", user_setting_path(user_setting), method: :delete, data: { confirm: "Confirm" } %></h4></li>
                <% end %>
              <% end %>
            </ul>

            <h4><%= link_to "Add Settings", new_user_setting_path, method: :get %></h4>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section id="team" class="team">
  <div class="container" data-aos="fade-up">
    <header class="section-header">
      <h2>My Profile</h2>
    </header>
    <div class="row gy-4">
      <div class="d-flex justify-content-center" data-aos="fade-up" data-aos-delay="100">
        <div class="member">
          <div class="member-info">
            <h4><%= @user.nick %></h4>
            <span><%= @user.role %></span>
            <p>Velit aut quia fugit et et. Dolorum ea voluptate vel tempore tenetur ipsa quae aut. Ipsum exercitationem iure minima enim corporis et voluptate.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/user_comments.html.erb
<section id="faq" class="faq" style="margin-top: 40px">
  <div class="container" data-aos="fade-up">
    <header class="section-header">
      <h2>My Comments</h2>
    </header>

    <div class="row">
      <div class="col-lg-12">
        <div class="accordion accordion-flush" id="faqlist1">
          <% unless @user_comments.blank? %>
            <% @user_comments.each do |comment| %>
              <div class="accordion-item">
                <h2 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-<%= comment.id %>">
                    Comment on <%= comment.commentable_type %>&nbsp;
                    <%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: "Are you sure?" } %>
                  </button>
                </h2>
                <div id="faq-content-<%= comment.id %>" class="accordion-collapse collapse" data-bs-parent="#faqlist1">
                  <div class="accordion-body">
                    <%= comment.text %>.
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <h2> Your comments will be displayed here!!! </h2>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/user_projects.html.erb
<section id="about" class="about" style="margin-top: 40px">
  <div class="container" data-aos="fade-up">
    <header class="section-header">
      <h2>My Projects</h2>
    </header>
    <div class="row gx-0">
      <div class="col-lg-12 d-flex flex-column justify-content-center" data-aos="fade-up" data-aos-delay="200">
        <% unless @user_projects.blank? %>
          <% @user_projects.each do |project| %>
            <div class="content" style="margin-top: 20px">
              <h3><%= project.title %></h3>
              <h2><%= project.description[0..150] %></h2>
                <p>
                  Relevance in 
                  <% project.regions[0..3].each do |region| %>
                    <%= region.name %>
                  <% end %>
                  ...
                </p>

                <p>
                  Spheres:  
                  <% project.spheres[0..3].each do |sphere| %>
                    <%= sphere.name %>
                  <% end %>
                  ...
                </p>

                <p>
                  We expect 
                  <% project.requirements_phrases[0..3].each do |requirement| %>
                    <%= requirement.name %>
                  <% end %>
                  ...
                </p>

              <div class="text-center text-lg-start">
                <a href="<%= project_path(project) %>" class="btn-read-more d-inline-flex align-items-center justify-content-center align-self-center">
                  <span>Read More</span>
                  <i class="bi bi-arrow-right"></i>
                </a>
              </div>
            </div>
          <% end %>
        <% else %>
          <h2> Your projects will be displayed here!!! </h2>
        <% end %>

        <%= paginate @user_projects %>
      </div>
    </div>
  </div>
</section>

app/views/users/user_proposals.html.erb
<section id="faq" class="faq" style="margin-top: 40px">
  <div class="container" data-aos="fade-up">
    <header class="section-header">
      <h2>My Proposal</h2>
    </header>

    <div class="row">
      <div class="col-lg-12">
        <div class="accordion accordion-flush" id="faqlist1">
          <% unless @user_proposals.blank? %>
            <% @user_proposals.each do |proposal| %>
              <div class="accordion-item">
                <h2 class="accordion-header">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#faq-content-<%= comment.id %>">
                    Proposal - <%= proposal.user %>&nbsp;
                    <%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: "Are you sure?" } %>
                  </button>
                </h2>
                <div id="faq-content-<%= comment.id %>" class="accordion-collapse collapse" data-bs-parent="#faqlist1">
                  <div class="accordion-body">
                    <%= comment.text %>.
                  </div>
                </div>
              </div>
            <% end %>
          <% else %>
            <h2> Your comments will be displayed here!!! </h2>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>