config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root 'users#home'
  get 'users/settings'
  get '/home', to: 'users#home'
  get '/about', to: 'users#about'
  get '/user_comments', to: 'users#user_comments'
  get '/user_projects', to: 'users#user_projects'
  get '/user_proposals', to: 'users#user_proposals'
  post '/search', to: 'search#search'

  devise_for :users

  resources :users
  resources :user_settings

  resources :comments

  resources :projects do
    resources :sponsor_proposals do
      get 'reject'
    end
  end

  namespace :api do
    namespace :v1 do
      resources :regions, only: [:index]
      resources :spheres, only: [:index]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user

  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/grading.rb
class Grading < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/project.rb
require 'elasticsearch/model'

class Project < ApplicationRecord
  include Elasticsearch::Model

  has_and_belongs_to_many :regions
  has_and_belongs_to_many :spheres
  has_and_belongs_to_many :requirements_phrases

  has_many :comments, as: :commentable, dependent: :destroy

  has_many :project_conditions
  has_many :sponsor_proposals, dependent: :destroy
  has_many :gradings
  belongs_to :user

  has_rich_text :development_plan

  validates :title, presence: true
  validates :description, presence: true

  paginates_per 5

  enum state: { active: 0, closed: 1 }
end

Project.__elasticsearch__.create_index!
Project.import

app/models/project_condition.rb
class ProjectCondition < ApplicationRecord
  has_and_belongs_to_many :projects
end

app/models/region.rb
class Region < ApplicationRecord
  has_and_belongs_to_many :projects
  has_many :user_settings, as: :settable
end

app/models/requirements_phrase.rb
class RequirementsPhrase < ApplicationRecord
  has_many :sponsor_conditions
  has_many :sponsor_proposals, through: :sponsor_conditions
  has_many :user_settings, as: :settable

  scope :for_sponsor, -> { where(purpose: :sponsor) }

  enum purpose: { sponsor: 0, project: 1 }
end

app/models/sphere.rb
class Sphere < ApplicationRecord
  has_and_belongs_to_many :projects
  has_many :user_settings, as: :settable
end

app/models/sponsar_condition.rb
# frozen_string_literal: true

class SponsorCondition < ApplicationRecord
  has_many :requirement_vocabularys
  belongs_to :sponsor_proposal
end

app/models/sponsar_proposal.rb
# frozen_string_literal: true

class SponsorProposal < ApplicationRecord
  has_many :sponsor_conditions
  belongs_to :project

  enum status: { open: 0, rejected: 1 }
end

app/models/sponsor_condition.rb
class SponsorCondition < ApplicationRecord
  belongs_to :sponsor_proposal
  belongs_to :requirements_phrase
end

app/models/sponsor_proposal.rb
class SponsorProposal < ApplicationRecord
  has_many :sponsor_conditions, dependent: :destroy
  has_many :requirements_phrases, through: :sponsor_conditions

  accepts_nested_attributes_for :sponsor_conditions

  belongs_to :project
  belongs_to :user

  enum status: { unblocked: 0, rejected: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  has_many :user_settings, dependent: :destroy
  has_many :projects, dependent: :destroy
  has_many :sponsor_proposals, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :contact, dependent: :destroy

  enum role: { sponsor: 0, businessman: 1 }

  scope :sponsors, -> { where(role: 0) }
end

app/models/user_setting.rb
class UserSetting < ApplicationRecord
  belongs_to :user
  belongs_to :settable, polymorphic: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(comment_params)
    redirect_back fallback_location: root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :user_id, :commentable_id, :commentable_type)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_regions, :load_spheres, :load_conditions, only: %i[new edit]
  before_action :find_project, only: %i[show edit update destroy]

  def index
    authorize Project
    projects = Projects::Filter.new(current_user).do_filter
    @projects = Kaminari.paginate_array(projects).page(params[:page]).per(5)
  end

  def show
    @requirements_phrases = RequirementsPhrase.all
    authorize @project
  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Projects::Creator.new(project_params, current_user).call
    authorize @project
    if @project
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
    authorize @project
  end

  def update
    authorize @project
    if @project.update(project_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    authorize @project
    @project.destroy
    redirect_to projects_path
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def find_project
    @project = Project.find(params[:id])
  end

  def load_regions
    @regions = Region.all
  end

  def load_conditions
    @conditions = RequirementsPhrase.for_sponsor
  end

  def load_spheres
    @spheres = Sphere.all
  end

  def project_params
    params.require(:project).permit(:title, :description, requirements_phrase_ids: [], region_ids: [], sphere_ids: [])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @search_list = Elasticsearch::Model.search(params[:text], Project).records.to_a
    respond_to do |format|
      format.js
      format.html { redirect_to root_path }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :init_user, only: %i[show edit update]

  def settings
    @user_settings = current_user.user_settings
  end

  def home; end

  def about; end

  def show; end

  def user_comments
    @user_comments = current_user.comments
  end

  def user_projects
    @user_projects = current_user.projects.page params[:page]
  end

  def user_proposals
    @user_proposals = current_user.sponsor_proposals
  end

  def destroy
    current_user.destroy
  end

  def edit;  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def init_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:nick, :email)
  end
end

app/helpers/project_helper.rb
module ProjectHelper
  def sponsor_proposals
    @project.sponsor_proposals.where({ status: 0 })
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Sponsorship Platform</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <link href="/assets/theme/vendor/aos/aos.css" rel="stylesheet">
    <link href="/assets/theme/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="/assets/theme/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/assets/theme/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/assets/theme/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="/assets/theme/css/style.css" rel="stylesheet">
    <link href="/assets/theme/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">


    <link href="/assets/theme/img/favicon.png" rel="icon">
    <link href="/assets/theme/img/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag "application" %> 
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <header id="header" class="header fixed-top">
      <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

        <a href="<%= root_path %>" class="logo d-flex align-items-center">
          <img src="/assets/theme/img/logo.png" alt="">
          <span>Sponsorify</span>
        </a>

        <nav id="navbar" class="navbar">
          <ul>
            <li>
              <%= form_with url: search_path, local: false, model: @text do |form| %>
                <div class="form-floating">         
                  <%= form.text_field :text, class: 'form-control', id: 'text', required: true %>
                  <%= form.label 'Search', for: 'text' %>
                  <%= form.submit 'Search', id: 'search_button', hidden: true %>
                </div>
              <% end %>  

              <div id='results' style='position: relative; z-index: 2;'></div>   
            </li>
            <li><a class="nav-link scrollto " href="<%= home_path %>">Home</a></li>
            <li><a class="nav-link scrollto" href="<%= about_path %>">About</a></li>
            <% if current_user %>
              <li class="dropdown"><a href="#"><span>Setting</span> <i class="bi bi-chevron-down"></i></a>
                <ul>
                  <li class="dropdown"><a href="<%= user_path(current_user) %>"><span>Me</span> <i class="bi bi-chevron-right"></i></a>
                    <ul>
                      <li><a href="<%= edit_user_path(current_user) %>">Edit</a></li>
                      <li><a href="<%= users_settings_path %>">My Settings</a></li>
                    </ul>
                  </li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                  <li><%= link_to 'Delete', user_path(current_user), method: :delete, data: { confirm: "Are you sure?" } %></li>
                </ul>
              </li>
              <li><a class="nav-link scrollto" href="<%= projects_path %>">Surf the Projects</a></li>
              <li><a class="nav-link scrollto" href="<%= user_comments_path %>">My Comments</a></li>
              <% if current_user.businessman? %>
                <li><a class="nav-link scrollto" href="<%= user_projects_path %>">My Projects</a></li>
                <li><a class="getstarted scrollto" href="<%= new_project_path %>">Get Started</a></li>
              <% else %>
                <li><a class="nav-link scrollto" href="<%= user_proposals_path %>">My Proposals</a></li>
              <% end %>
            <% end %>
          </ul>
          <i class="bi bi-list mobile-nav-toggle"></i>
        </nav>

      </div>
    </header>
  
    <%= yield %>

    <footer id="footer" class="footer">

      <div class="footer-top">
        <div class="container">
          <div class="row gy-4">
            <div class="col-lg-5 col-md-12 footer-info">
              <a href="<%= home_path %>" class="logo d-flex align-items-center">
                <img src="/assets/theme/img/logo.png" alt="">
                <span>Sponsorify</span>
              </a>
              <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
            </div>

            <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
              <h4>Contact Us</h4>
              <p>
                A108 Adam Street <br>
                New York, NY 535022<br>
                United States <br><br>
                <strong>Phone:</strong> +1 5589 55488 55<br>
                <strong>Email:</strong> info@example.com<br>
              </p>

            </div>

          </div>
        </div>
      </div>

      <div class="container">
        <div class="copyright">
          &copy; Copyright <strong><span>Sponsorify</span></strong>. All Rights Reserved
        </div>
      </div>
    </footer>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <script src="/assets/theme/vendor/purecounter/purecounter.js"></script>
    <script src="/assets/theme/vendor/aos/aos.js"></script>
    <script src="/assets/theme/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/assets/theme/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="/assets/theme/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="/assets/theme/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="/assets/theme/vendor/php-email-form/validate.js"></script>

    <script src="/assets/theme/js/main.js"></script>
  </body>
</html>

<script>
  $('#text').on('input', () =>
  {
    $('#search_button').click()
  })
</script>